--CREATE DATABASE RaceDay;

--CREATE TABLE ORGANISERS(
--OrganiserID INT NOT NULL PRIMARY KEY,
--OrganiserName VARCHAR(30) NOT NULL,
--OrganiserSurname VARCHAR(30) NOT NULL,
--OrganiserAddress VARCHAR(60) NOT NULL
--);

--CREATE TABLE PARTICIPANTS(
--ParticipantID INT NOT NULL PRIMARY KEY,
--ParticipantName VARCHAR(30) NOT NULL,
--ParticipantSurname VARCHAR(30) NOT NULL,
--ParticipantEmail VARCHAR(30),
--ParticipantContact INT NOT NULL
--);

--CREATE TABLE EVENTS(
--EventID INT NOT NULL PRIMARY KEY,
--EventName VARCHAR(80) NOT NULL,
--[Description] VARCHAR(100) NOT NULL,
--[Date] VARCHAR(9) NOT NULL,
--[Location] VARCHAR(40) NOT NULL,
--Distance VARCHAR(5000) NOT NULL,
--EventType VARCHAR(30),
--OrganiserID INT NOT NULL,

--FOREIGN KEY (OrganiserID) REFERENCES ORGANISERS(OrganiserID)
--);



--CREATE TABLE CATEGORIES(
--CategoryID INT NOT NULL PRIMARY KEY,
--CategoryName VARCHAR(30) NOT NULL,
--Age INT NOT NULL,
--OrganiserID INT NOT NULL,
--EventID INT NOT NULL,

--FOREIGN KEY (OrganiserID) REFERENCES ORGANISERS(OrganiserID),
--FOREIGN KEY (EventID) REFERENCES EVENTS(EventID)
--);

--CREATE TABLE ENROLMENT(
--EnrolmentID INT NOT NULL PRIMARY KEY,
--EventID INT NOT NULL,
--ParticipantID INT NOT NULL,
--OrganiserID INT NOT NULL,
--CategoryID INT NOT NULL,
--EnrolDate VARCHAR(9) NOT NULL,

--FOREIGN KEY (EventID) REFERENCES EVENTS(EventID),
--FOREIGN KEY (ParticipantID) REFERENCES PARTICIPANTS(ParticipantID),
--FOREIGN KEY (OrganiserID) REFERENCES ORGANISERS(OrganiserID),
--FOREIGN KEY (CategoryID) REFERENCES CATEGORIES(CategoryID)
--);

--CREATE TABLE RESULTS(
--ResultID INT NOT NULL PRIMARY KEY,
--Finish_time VARCHAR(20) NOT NULL,
--Finishing_Positions INT NOT NULL,
--EnrolmentID INT NOT NULL,

--FOREIGN KEY (EnrolmentID) REFERENCES ENROLMENT(EnrolmentID)
--);

--CREATE TABLE HISTORY(
--HistoryID INT NOT NULL PRIMARY KEY,
--ResultID INT NOT NULL,
--ParticipantID INT NOT NULL,
--ViewDate VARCHAR(9) NOT NULL,

--FOREIGN KEY (ResultID) REFERENCES RESULTS(ResultID),
--FOREIGN KEY (ParticipantID) REFERENCES PARTICIPANTS(ParticipantID)
--);